import assert from "node:assert/strict";
import test from "node:test";
import { HermesIncrementalSyncService, type HermesIncrementalCheckpoint, type HermesIncrementalCheckpointStore, type HermesSessionPayload, type HermesSessionRow, type HermesStateReader } from "../src/index.js";

class Reader implements HermesStateReader {
  sessions = new Map<string, HermesSessionPayload>();
  async inspect() { return { schemaVersion: "30", tables: ["sessions","messages"], columns: { sessions: ["id","source","profile_name","title","message_count","tool_call_count","started_at","ended_at","last_activity_at","end_reason","archived","expiry_finalized","hidden","parent_session_id","chat_id","chat_type","thread_id","user_id"], messages: ["id","session_id","role","content","tool_call_id","tool_calls","tool_name","timestamp","finish_reason","reasoning","platform_message_id","_compressed_summary","active","compacted","display_kind","display_metadata"] } }; }
  async listSessions({ afterSessionId, limit }: { afterSessionId?: string; limit: number }) { return [...this.sessions.values()].map(x=>x.session).filter(x=>afterSessionId===undefined || x.id>afterSessionId).sort((a,b)=>a.id.localeCompare(b.id)).slice(0,limit); }
  async readSession(id: string) { const value=this.sessions.get(id); if(!value) throw new Error("missing"); return structuredClone(value); }
}
class Checkpoints implements HermesIncrementalCheckpointStore { value?: HermesIncrementalCheckpoint; saves=0; async load(){return this.value&&structuredClone(this.value)} async save(v: HermesIncrementalCheckpoint){this.value=structuredClone(v);this.saves+=1;} }
function session(id:string, contents:string[]): HermesSessionPayload { const now=1_789_470_000; const row: HermesSessionRow={id,source:"cli",messageCount:contents.length,toolCallCount:0,startedAt:now,lastActivityAt:now+contents.length,archived:false,expiryFinalized:false,hidden:false}; return {session:row,messages:contents.map((content,i)=>({id:i+1,sessionId:id,role:i%2===0?"user":"assistant",content,timestamp:now+i,compressedSummary:false,active:true,compacted:false}))}; }
function service(reader:Reader, cp:Checkpoints, receipts:string[]){ return new HermesIncrementalSyncService({reader,checkpointStore:cp,distillation:{async run(input:any){receipts.push(input.sourceId);return {receiptId:`dist_${receipts.length}`,scope:input.scope,sourceType:input.sourceType,sourceId:input.sourceId,idempotencyKey:"x",provider:"test",distillationPolicyVersion:"d",semanticPolicyVersion:"s",canonicalizationPolicyVersion:"c",retentionPolicyVersion:"r",adapterVersion:"a",curationProvider:"q",admissionPolicyVersion:"p",providerUnitCount:0,curationDecisionCount:0,curationOutcomes:{canonical_candidate:0,canonical_merge:0,duplicate:0,rejected:0,pending_review:0},curationCoverageComplete:true,admissionComplete:true,candidateIds:[],canonicalMemoryIds:[],status:"complete",errors:[],warnings:[],canonicalizationOutcome:"no_memory_worthy_content",retentionState:"preserved",pruneEligible:false,attempts:1,createdAt:"2026-09-15T00:00:00Z",updatedAt:"2026-09-15T00:00:00Z"} as any;}},scope:{tenantId:"t",lifeDid:"did:arthurverse:nancy",memoryNamespace:"private-beta"},origin:{lifeDid:"did:arthurverse:nancy",runtimeId:"hermes"},policies:{distillationPolicyVersion:"d",canonicalizationPolicyVersion:"c",admissionPolicyVersion:"p",retentionPolicyVersion:"r"},pageSize:1}); }

test("baseline current establishes watermark without historical ingestion", async()=>{ const reader=new Reader(); const cp=new Checkpoints(); const receipts:string[]=[]; reader.sessions.set("a",session("a",["historical durable fact"])); reader.sessions.set("b",session("b",["historical preference"])); const sync=service(reader,cp,receipts); const baseline=await sync.baselineCurrent(); assert.equal(baseline.scanned,2); assert.equal(baseline.ingested,0); assert.equal(receipts.length,0); const replay=await service(reader,cp,receipts).runOnce(); assert.equal(replay.changed,0); assert.equal(replay.unchanged,2); });

test("incremental sync discovers new sessions, mutable changes, replay idempotence and restart checkpoint", async()=>{ const reader=new Reader(); const cp=new Checkpoints(); const receipts:string[]=[]; reader.sessions.set("a",session("a",["My durable preference is tea."])); let run=await service(reader,cp,receipts).runOnce(); assert.equal(run.changed,1); assert.equal(run.ingested,1); assert.equal(run.skipped,0); run=await service(reader,cp,receipts).runOnce(); assert.equal(run.changed,0); assert.equal(run.unchanged,1); reader.sessions.set("a",session("a",["My durable preference is tea.","Acknowledged.","My long-term project is Nancy Private Beta."])); run=await service(reader,cp,receipts).runOnce(); assert.equal(run.changed,1); reader.sessions.set("b",session("b",["開始"])); run=await service(reader,cp,receipts).runOnce(); assert.equal(run.changed,1); assert.equal(run.skipped,1); assert.equal(run.unchanged,1); assert.equal(receipts.length,2); assert.ok(cp.saves>=3); });

test("live incremental sync skips pure greeting but revisits the same session when durable user content arrives", async()=>{ const reader=new Reader(); const cp=new Checkpoints(); const receipts:string[]=[]; reader.sessions.set("g",session("g",["你好","你好！我是 Genesis-001。"])); let run=await service(reader,cp,receipts).runOnce(); assert.equal(run.changed,1); assert.equal(run.skipped,1); assert.equal(run.ingested,0); assert.equal(receipts.length,0); const skippedFingerprint=cp.value?.sessions.g; assert.ok(skippedFingerprint); reader.sessions.set("g",session("g",["你好","你好！我是 Genesis-001。","我叫 Arthur，請以後叫我 Arthur。"])); run=await service(reader,cp,receipts).runOnce(); assert.equal(run.changed,1); assert.equal(run.skipped,0); assert.equal(run.ingested,1); assert.equal(receipts.length,1); assert.notEqual(cp.value?.sessions.g,skippedFingerprint); });
