import type { MemoryId } from "../domain/types.js";

export const OBSIDIAN_PROJECTION_SCHEMA_VERSION = "1" as const;

export type ObsidianProjectionNodeKind =
  | "memory"
  | "memory_class"
  | "memory_type"
  | "namespace"
  | "source_type";

/**
 * One deterministic Markdown file generated by DLMF for an Obsidian vault.
 *
 * Files described by this contract are projections only. They are never an
 * authority for Canonical Memory and may be deleted/rebuilt from DLMF.
 */
export interface ObsidianProjectionNote {
  readonly path: string;
  readonly content: string;
  readonly managed: true;
  readonly nodeKind: ObsidianProjectionNodeKind;
  readonly sourceMemoryId?: MemoryId;
}

export interface ObsidianProjectionBundle {
  readonly schemaVersion: typeof OBSIDIAN_PROJECTION_SCHEMA_VERSION;
  readonly memoryId: MemoryId;
  readonly canonicalRevision: number;
  readonly commitSeq: number;
  readonly notes: readonly ObsidianProjectionNote[];
}

export interface ObsidianCanonicalProjectionOptions {
  /** Root directory inside the user-owned vault. Defaults to `90 DLMF`. */
  readonly managedRoot?: string;
}
